package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// buildEnumAdapter emits the pbgql/<enum_lower>.go source for a single proto enum.
// pbImport is the Go import path of the pb package.
func buildEnumAdapter(e *protogen.Enum, pbImport string) string {
	name := e.GoIdent.GoName
	lower := strings.ToLower(name)
	_ = lower // filename is decided by caller

	var sb strings.Builder

	// Package + import comment.
	fmt.Fprintf(&sb, "// Package pbgql provides GraphQL marshal/unmarshal adapters for proto enums.\n")
	fmt.Fprintf(&sb, "// Code generated by protoc-gen-go-graphql. DO NOT EDIT.\n")
	sb.WriteString("package pbgql\n")
	sb.WriteString("\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"io\"\n")
	sb.WriteString("\t\"strconv\"\n")
	sb.WriteString("\n")
	sb.WriteString("\t\"github.com/99designs/gqlgen/graphql\"\n")
	fmt.Fprintf(&sb, "\tpb %q\n", pbImport)
	sb.WriteString(")\n")
	sb.WriteString("\n")

	// Type alias.
	fmt.Fprintf(&sb, "// %s is an alias of the pb enum, so fields typed pb.%s bind to it directly.\n", name, name)
	fmt.Fprintf(&sb, "type %s = pb.%s\n", name, name)
	sb.WriteString("\n")

	// Marshal function.
	fmt.Fprintf(&sb, "// Marshal%s writes the proto enum's value NAME (protojson form), e.g. %q.\n",
		name, e.Values[1].Desc.Name()) // use second value as example (skip _UNSPECIFIED)
	fmt.Fprintf(&sb, "func Marshal%s(v pb.%s) graphql.Marshaler {\n", name, name)
	sb.WriteString("\treturn graphql.WriterFunc(func(w io.Writer) {\n")
	sb.WriteString("\t\t_, _ = io.WriteString(w, strconv.Quote(v.String()))\n")
	sb.WriteString("\t})\n")
	sb.WriteString("}\n")
	sb.WriteString("\n")

	// Unmarshal function.
	fmt.Fprintf(&sb, "// Unmarshal%s parses a proto enum value name back to the pb enum.\n", name)
	fmt.Fprintf(&sb, "func Unmarshal%s(v any) (pb.%s, error) {\n", name, name)
	sb.WriteString("\ts, ok := v.(string)\n")
	sb.WriteString("\tif !ok {\n")
	fmt.Fprintf(&sb, "\t\treturn 0, fmt.Errorf(\"%s must be a string, got %%T\", v)\n", name)
	sb.WriteString("\t}\n")
	fmt.Fprintf(&sb, "\tval, ok := pb.%s_value[s]\n", name)
	sb.WriteString("\tif !ok {\n")
	fmt.Fprintf(&sb, "\t\treturn 0, fmt.Errorf(\"invalid %s %%q\", s)\n", name)
	sb.WriteString("\t}\n")
	fmt.Fprintf(&sb, "\treturn pb.%s(val), nil\n", name)
	sb.WriteString("}\n")

	return sb.String()
}
