package generator

import "fmt"

// buildGoGenerate emits the generate.go file content for the gqlapi package.
// It contains the //go:generate directive that runs gqlgenrun.
//
// runnerPkg is the full import path of the runner binary
// (e.g. "github.com/gopherex/protoc-gen-go-graphql/cmd/gqlgenrun").
// pkgName is the Go package name for this file (e.g. "gqlapi").
func buildGoGenerate(runnerPkg, pkgName string) string {
	return fmt.Sprintf(`// Code generated by protoc-gen-go-graphql. DO NOT EDIT.
package %s

//go:generate go run %s --config gqlgen.yml
`, pkgName, runnerPkg)
}
