package generator

import "fmt"

// buildGoGenerate emits the generate.go file content for the gqlapi package.
// It contains the //go:generate directive that runs gqlgenrun.
// modulePath is the module root path (e.g. "github.com/gopherex/protoc-gen-go-graphql").
func buildGoGenerate(modulePath string) string {
	return fmt.Sprintf(`// Code generated by protoc-gen-go-graphql. DO NOT EDIT.
package gqlapi

//go:generate go run %s/cmd/gqlgenrun --config gqlgen.yml
`, modulePath)
}
