package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// buildResolvers emits the resolver.go source for the gqlapi package.
// Parameters:
//   - f: the proto file descriptor
//   - pbImport: Go import path of the pb package (e.g. "...example/gen")
//   - pbgqlImport: Go import path of the pbgql package (e.g. "...example/gen/gqlapi/pbgql")
//   - execImport: Go import path of the exec package (e.g. "...example/gen/gqlapi/exec")
//   - runtimeImport: Go import path of the runtime package
func buildResolvers(f *protogen.File, pbImport, pbgqlImport, execImport, runtimeImport string) string {
	var sb strings.Builder

	// Collect oneof info.
	msgInfo := analyzeMessages(f)
	ois := collectOneofs(f, msgInfo)

	// Index by message name.
	outputOneofsByMsg := map[string][]oneofInfo{} // msgGoName → output oneofs
	inputOneofsByMsg := map[string]oneofInfo{}     // reqMsgGoName → input oneof (at most one per request)
	for _, oi := range ois {
		if oi.IsOutput {
			outputOneofsByMsg[oi.MsgGoName] = append(outputOneofsByMsg[oi.MsgGoName], oi)
		}
		if oi.IsInput {
			inputOneofsByMsg[oi.MsgGoName] = oi
		}
	}

	// Determine if pbgql import is needed (any oneof present).
	needsPbgql := len(ois) > 0

	sb.WriteString("// Code generated by protoc-gen-go-graphql. DO NOT EDIT.\n")
	sb.WriteString("package gqlapi\n")
	sb.WriteString("\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"context\"\n")
	sb.WriteString("\n")
	fmt.Fprintf(&sb, "\tpb %q\n", pbImport)
	if needsPbgql {
		fmt.Fprintf(&sb, "\t%q\n", pbgqlImport)
	}
	fmt.Fprintf(&sb, "\t%q\n", runtimeImport)
	fmt.Fprintf(&sb, "\t%q\n", execImport)
	sb.WriteString(")\n")
	sb.WriteString("\n")

	// Resolver struct: one field per service (svcName pb.SvcServer).
	sb.WriteString("// Resolver delegates GraphQL operations to the gRPC server implementation.\n")
	sb.WriteString("// It implements exec.ResolverRoot and each sub-resolver interface,\n")
	sb.WriteString("// delegating to the gRPC server with zero proto<->model conversion.\n")
	sb.WriteString("type Resolver struct {\n")
	for _, svc := range f.Services {
		fmt.Fprintf(&sb, "\t%s pb.%sServer\n", svc.GoName, svc.GoName)
	}
	sb.WriteString("}\n")
	sb.WriteString("\n")

	// Collect info needed for sub-resolvers.
	// Map: resolver type name → methods
	type resolverMethod struct {
		receiverType string
		goName       string
		inputType    string
		outputType   string
		opType       string
		streamType   string // for subscriptions
		svcName      string
	}

	// Collect map-field resolvers (for output types with map fields).
	type mapFieldResolver struct {
		ownerType     string // e.g. "Book"
		ownerPbType   string // Go type of the receiver, e.g. "*pb.Book" or "*pbgql.SearchResponseResultBook"
		ownerPkg      string // "pb" or "pbgql"
		fieldName     string // camelCase, e.g. "tags"
		mapGetter     string // e.g. "GetTags" (relative to embedded pb type)
		embeddedField string // for wrappers: the embedded pb msg name; empty for direct pb types
	}
	var mapResolvers []mapFieldResolver

	// First: direct pb message map fields.
	for _, msg := range f.Messages {
		if msg.Desc.IsMapEntry() {
			continue
		}
		for _, field := range msg.Fields {
			if !field.Desc.IsMap() {
				continue
			}
			camel := fieldName(string(field.Desc.Name()))
			getter := "Get" + string(field.GoName)
			mapResolvers = append(mapResolvers, mapFieldResolver{
				ownerType:   msg.GoIdent.GoName,
				ownerPbType: "*pb." + msg.GoIdent.GoName,
				ownerPkg:    "pb",
				fieldName:   camel,
				mapGetter:   getter,
			})
		}
	}

	// Second: union member wrapper types that embed a pb message with map fields.
	// For each output oneof's variants that wrap a message with map fields, we need
	// a field resolver on the wrapper type too.
	for _, oi := range ois {
		if !oi.IsOutput {
			continue
		}
		for _, v := range oi.Variants {
			if !v.IsMessage || v.Msg == nil {
				continue
			}
			for _, field := range v.Msg.Fields {
				if !field.Desc.IsMap() {
					continue
				}
				camel := fieldName(string(field.Desc.Name()))
				getter := "Get" + string(field.GoName)
				// The receiver is the wrapper type (in pbgql), not the pb type.
				mapResolvers = append(mapResolvers, mapFieldResolver{
					ownerType:     v.WrapperGoName,
					ownerPbType:   "*pbgql." + v.WrapperGoName,
					ownerPkg:      "pbgql",
					fieldName:     camel,
					mapGetter:     getter,
					embeddedField: "", // Go finds GetTags via embedding
				})
			}
		}
	}

	// Determine which output types need a sub-resolver:
	//   - types with map fields (for JSON scalar field resolvers)
	//   - types with output oneofs (for union field resolvers)
	resolverTypes := map[string]bool{} // e.g. "Book" → true
	for _, mr := range mapResolvers {
		resolverTypes[mr.ownerType] = true
	}
	for _, oi := range ois {
		if oi.IsOutput {
			resolverTypes[oi.MsgGoName] = true
		}
	}

	// Operation sub-resolver types: queryResolver, mutationResolver, etc.
	opTypes := map[string]bool{}
	for _, svc := range f.Services {
		for _, m := range svc.Methods {
			op := operationType(m)
			opTypes[strings.ToLower(op)] = true
		}
	}

	// ResolverRoot interface methods.
	// For each output type that has map/oneof fields → <TypeName>() exec.<TypeName>Resolver
	// For each op type → <OpType>() exec.<OpType>Resolver
	// Sort resolverTypes for deterministic output.
	resolverTypesSorted := sortedKeys(resolverTypes)
	for _, typeName := range resolverTypesSorted {
		recvName := strings.ToLower(typeName[:1]) + typeName[1:] + "Resolver"
		fmt.Fprintf(&sb, "func (r *Resolver) %s() exec.%sResolver { return %s{r} }\n",
			typeName, typeName, recvName)
	}
	for _, opType := range []string{"Query", "Mutation", "Subscription"} {
		if opTypes[strings.ToLower(opType)] {
			recvName := strings.ToLower(opType) + "Resolver"
			fmt.Fprintf(&sb, "func (r *Resolver) %s() exec.%sResolver { return %s{r} }\n",
				opType, opType, recvName)
		}
	}
	sb.WriteString("\n")

	// Declare sub-resolver struct types.
	for _, typeName := range resolverTypesSorted {
		recvName := strings.ToLower(typeName[:1]) + typeName[1:] + "Resolver"
		fmt.Fprintf(&sb, "type %s struct{ *Resolver }\n", recvName)
	}
	for _, opType := range []string{"Query", "Mutation", "Subscription"} {
		if opTypes[strings.ToLower(opType)] {
			recvName := strings.ToLower(opType) + "Resolver"
			fmt.Fprintf(&sb, "type %s struct{ *Resolver }\n", recvName)
		}
	}
	sb.WriteString("\n")

	// Map field resolver methods.
	for _, mr := range mapResolvers {
		recvName := strings.ToLower(mr.ownerType[:1]) + mr.ownerType[1:] + "Resolver"
		capField := strings.ToUpper(mr.fieldName[:1]) + mr.fieldName[1:]
		fmt.Fprintf(&sb, "// %s exposes the proto map field as a JSON scalar (field\n", capField)
		fmt.Fprintf(&sb, "// resolver, because the JSON scalar's Go type `any` cannot bind a concrete map).\n")
		fmt.Fprintf(&sb, "func (r %s) %s(ctx context.Context, obj %s) (any, error) {\n",
			recvName, capField, mr.ownerPbType)
		fmt.Fprintf(&sb, "\treturn obj.%s(), nil\n", mr.mapGetter)
		sb.WriteString("}\n")
		sb.WriteString("\n")
	}

	// Output oneof union field resolvers.
	for _, oi := range ois {
		if !oi.IsOutput {
			continue
		}
		recvName := strings.ToLower(oi.MsgGoName[:1]) + oi.MsgGoName[1:] + "Resolver"
		capField := strings.ToUpper(oi.GQLFieldName[:1]) + oi.GQLFieldName[1:]
		fmt.Fprintf(&sb, "// %s resolves the oneof field %q as a %s union.\n",
			capField, oi.ProtoName, oi.UnionGQLName)
		fmt.Fprintf(&sb, "// It wraps the pb oneof variant into the appropriate pbgql wrapper type.\n")
		fmt.Fprintf(&sb, "func (r %s) %s(ctx context.Context, obj *pb.%s) (pbgql.%s, error) {\n",
			recvName, capField, oi.MsgGoName, oi.InterfaceGoName)
		fmt.Fprintf(&sb, "\treturn pbgql.Wrap%s(obj), nil\n", oi.InterfaceGoName)
		sb.WriteString("}\n")
		sb.WriteString("\n")
	}

	// Operation resolver methods.
	for _, svc := range f.Services {
		for _, m := range svc.Methods {
			op := operationType(m)
			recvName := strings.ToLower(op) + "Resolver"
			methodName := m.GoName
			inputGoName := m.Input.GoIdent.GoName
			outputType := m.Output.GoIdent.GoName

			switch op {
			case "Query", "Mutation":
				if inputOI, hasInputOneof := inputOneofsByMsg[inputGoName]; hasInputOneof {
					// Input has a oneof: the resolver receives the intermediate pbgql struct.
					fmt.Fprintf(&sb, "func (r %s) %s(ctx context.Context, input pbgql.%s) (*pb.%s, error) {\n",
						recvName, methodName, inputOI.MsgInputGoName, outputType)
					fmt.Fprintf(&sb, "\tresp, err := r.%s.%s(ctx, pbgql.ToPb%s(&input))\n",
						svc.GoName, methodName, inputGoName)
				} else {
					// Normal input: bind directly to pb.
					fmt.Fprintf(&sb, "func (r %s) %s(ctx context.Context, input pb.%s) (*pb.%s, error) {\n",
						recvName, methodName, inputGoName, outputType)
					fmt.Fprintf(&sb, "\tresp, err := r.%s.%s(ctx, &input)\n", svc.GoName, methodName)
				}
				sb.WriteString("\tif err != nil {\n")
				sb.WriteString("\t\treturn nil, runtime.GraphQLError(ctx, err)\n")
				sb.WriteString("\t}\n")
				sb.WriteString("\treturn resp, nil\n")
				sb.WriteString("}\n")
				sb.WriteString("\n")

			case "Subscription":
				// The streaming message type: for server-streaming the output IS the
				// message type (not a wrapper). For golden, WatchBooks returns stream Book,
				// so m.Output.GoIdent.GoName is "Book".
				streamMsgType := outputType
				fmt.Fprintf(&sb, "func (r %s) %s(ctx context.Context, input pb.%s) (<-chan *pb.%s, error) {\n",
					recvName, methodName, inputGoName, streamMsgType)
				fmt.Fprintf(&sb, "\treturn runtime.PumpServerStream[pb.%s](ctx, func(ss *runtime.StreamServer[pb.%s]) error {\n",
					streamMsgType, streamMsgType)
				fmt.Fprintf(&sb, "\t\treturn r.%s.%s(&input, ss)\n", svc.GoName, methodName)
				sb.WriteString("\t}), nil\n")
				sb.WriteString("}\n")
				sb.WriteString("\n")
			}
		}
	}

	return sb.String()
}

// sortedKeys returns the keys of m in sorted order.
func sortedKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	// Sort deterministically.
	for i := 0; i < len(keys); i++ {
		for j := i + 1; j < len(keys); j++ {
			if keys[i] > keys[j] {
				keys[i], keys[j] = keys[j], keys[i]
			}
		}
	}
	return keys
}


