package generator

import (
	"fmt"
	"strings"
)

// wrapperScalars lists the WKT wrapper types that need per-type pbgql adapters.
var wrapperScalars = []struct {
	GQLName   string // e.g. "DoubleValue"
	WktGoType string // e.g. "DoubleValue" (wrapperspb.DoubleValue)
}{
	{"DoubleValue", "DoubleValue"},
	{"FloatValue", "FloatValue"},
	{"Int32Value", "Int32Value"},
	{"UInt32Value", "UInt32Value"},
	{"Int64Value", "Int64Value"},
	{"UInt64Value", "UInt64Value"},
	{"BoolValue", "BoolValue"},
	{"StringValue", "StringValue"},
	{"BytesValue", "BytesValue"},
}

// buildWKTAdapters emits pbgql/wkt_adapters.go containing Marshal/Unmarshal funcs
// for each wrapper type scalar used in the file. Returns "" when none are used.
func buildWKTAdapters(usedScalars map[string]bool) string {
	// Collect only wrapper types that are actually used.
	var used []struct {
		GQLName   string
		WktGoType string
	}
	for _, ws := range wrapperScalars {
		if usedScalars[ws.GQLName] {
			used = append(used, ws)
		}
	}
	if len(used) == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString("// Package pbgql provides GraphQL binding adapters for proto wrapper types.\n")
	sb.WriteString("// Code generated by protoc-gen-go-graphql. DO NOT EDIT.\n")
	sb.WriteString("package pbgql\n")
	sb.WriteString("\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"encoding/json\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"io\"\n")
	sb.WriteString("\n")
	sb.WriteString("\t\"github.com/99designs/gqlgen/graphql\"\n")
	sb.WriteString("\t\"google.golang.org/protobuf/encoding/protojson\"\n")
	sb.WriteString("\t\"google.golang.org/protobuf/types/known/wrapperspb\"\n")
	sb.WriteString(")\n")
	sb.WriteString("\n")

	for _, ws := range used {
		emitWrapperAdapter(&sb, ws.GQLName, ws.WktGoType)
	}

	return sb.String()
}

func emitWrapperAdapter(sb *strings.Builder, gqlName, wktType string) {
	// Type alias so the scalar's Go binding matches *wrapperspb.XxxValue directly.
	fmt.Fprintf(sb, "// %s is an alias for *wrapperspb.%s so gqlgen's autobind can\n", gqlName, wktType)
	fmt.Fprintf(sb, "// reference it as a scalar type by the short wrapper name.\n")
	fmt.Fprintf(sb, "type %s = wrapperspb.%s\n", gqlName, wktType)
	sb.WriteString("\n")

	// Marshal: use protojson which emits the bare inner value (or null for nil).
	fmt.Fprintf(sb, "// Marshal%s writes the proto wrapper via protojson (bare inner value or null).\n", gqlName)
	fmt.Fprintf(sb, "func Marshal%s(v *wrapperspb.%s) graphql.Marshaler {\n", gqlName, wktType)
	sb.WriteString("\treturn graphql.WriterFunc(func(w io.Writer) {\n")
	sb.WriteString("\t\tif v == nil {\n")
	sb.WriteString("\t\t\t_, _ = io.WriteString(w, \"null\")\n")
	sb.WriteString("\t\t\treturn\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t\tb, err := protojson.Marshal(v)\n")
	sb.WriteString("\t\tif err != nil {\n")
	sb.WriteString("\t\t\tpanic(err)\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t\t_, _ = w.Write(b)\n")
	sb.WriteString("\t})\n")
	sb.WriteString("}\n")
	sb.WriteString("\n")

	// Unmarshal: accept any JSON value (including null) and convert to *wrapperspb.XxxValue.
	// We re-encode the raw value as JSON bytes and unmarshal via protojson.
	fmt.Fprintf(sb, "// Unmarshal%s parses a JSON value into *wrapperspb.%s (nil for null/nil input).\n", gqlName, wktType)
	fmt.Fprintf(sb, "func Unmarshal%s(v any) (*wrapperspb.%s, error) {\n", gqlName, wktType)
	sb.WriteString("\tif v == nil {\n")
	sb.WriteString("\t\treturn nil, nil\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\traw, err := json.Marshal(v)\n")
	sb.WriteString("\tif err != nil {\n")
	fmt.Fprintf(sb, "\t\treturn nil, fmt.Errorf(\"%s unmarshal: %%w\", err)\n", gqlName)
	sb.WriteString("\t}\n")
	fmt.Fprintf(sb, "\tout := &wrapperspb.%s{}\n", wktType)
	sb.WriteString("\tif err := protojson.Unmarshal(raw, out); err != nil {\n")
	fmt.Fprintf(sb, "\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", gqlName)
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn out, nil\n")
	sb.WriteString("}\n")
	sb.WriteString("\n")
}
