// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: graphqlopt/graphql.proto

package graphqlopt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED Operation = 0 // use idempotency_level
	Operation_QUERY                 Operation = 1
	Operation_MUTATION              Operation = 2
	Operation_SUBSCRIPTION          Operation = 3
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "QUERY",
		2: "MUTATION",
		3: "SUBSCRIPTION",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"QUERY":                 1,
		"MUTATION":              2,
		"SUBSCRIPTION":          3,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_graphqlopt_graphql_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_graphqlopt_graphql_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_graphqlopt_graphql_proto_rawDescGZIP(), []int{0}
}

type OneofInputMode int32

const (
	OneofInputMode_ONEOF_INPUT_UNSPECIFIED OneofInputMode = 0
	OneofInputMode_ONEOF_DIRECTIVE         OneofInputMode = 1
	OneofInputMode_ALL_NULLABLE            OneofInputMode = 2
)

// Enum value maps for OneofInputMode.
var (
	OneofInputMode_name = map[int32]string{
		0: "ONEOF_INPUT_UNSPECIFIED",
		1: "ONEOF_DIRECTIVE",
		2: "ALL_NULLABLE",
	}
	OneofInputMode_value = map[string]int32{
		"ONEOF_INPUT_UNSPECIFIED": 0,
		"ONEOF_DIRECTIVE":         1,
		"ALL_NULLABLE":            2,
	}
)

func (x OneofInputMode) Enum() *OneofInputMode {
	p := new(OneofInputMode)
	*p = x
	return p
}

func (x OneofInputMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OneofInputMode) Descriptor() protoreflect.EnumDescriptor {
	return file_graphqlopt_graphql_proto_enumTypes[1].Descriptor()
}

func (OneofInputMode) Type() protoreflect.EnumType {
	return &file_graphqlopt_graphql_proto_enumTypes[1]
}

func (x OneofInputMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OneofInputMode.Descriptor instead.
func (OneofInputMode) EnumDescriptor() ([]byte, []int) {
	return file_graphqlopt_graphql_proto_rawDescGZIP(), []int{1}
}

type FileOptions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PbPackage            string                 `protobuf:"bytes,2,opt,name=pb_package,json=pbPackage,proto3" json:"pb_package,omitempty"`                                    // import path for autobind (overrides go_package)
	SchemaFilename       string                 `protobuf:"bytes,3,opt,name=schema_filename,json=schemaFilename,proto3" json:"schema_filename,omitempty"`                     // default schema.graphql
	GqlgenConfigFilename string                 `protobuf:"bytes,4,opt,name=gqlgen_config_filename,json=gqlgenConfigFilename,proto3" json:"gqlgen_config_filename,omitempty"` // default gqlgen.yml
	ExecPackage          string                 `protobuf:"bytes,5,opt,name=exec_package,json=execPackage,proto3" json:"exec_package,omitempty"`
	ExecFilename         string                 `protobuf:"bytes,6,opt,name=exec_filename,json=execFilename,proto3" json:"exec_filename,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_graphqlopt_graphql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphqlopt_graphql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_graphqlopt_graphql_proto_rawDescGZIP(), []int{0}
}

func (x *FileOptions) GetPbPackage() string {
	if x != nil {
		return x.PbPackage
	}
	return ""
}

func (x *FileOptions) GetSchemaFilename() string {
	if x != nil {
		return x.SchemaFilename
	}
	return ""
}

func (x *FileOptions) GetGqlgenConfigFilename() string {
	if x != nil {
		return x.GqlgenConfigFilename
	}
	return ""
}

func (x *FileOptions) GetExecPackage() string {
	if x != nil {
		return x.ExecPackage
	}
	return ""
}

func (x *FileOptions) GetExecFilename() string {
	if x != nil {
		return x.ExecFilename
	}
	return ""
}

type ServiceOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          bool                   `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	NamePrefix    string                 `protobuf:"bytes,2,opt,name=name_prefix,json=namePrefix,proto3" json:"name_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_graphqlopt_graphql_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphqlopt_graphql_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_graphqlopt_graphql_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *ServiceOptions) GetNamePrefix() string {
	if x != nil {
		return x.NamePrefix
	}
	return ""
}

type MethodOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          bool                   `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`                                       // omit this method from the GraphQL API
	Operation     Operation              `protobuf:"varint,2,opt,name=operation,proto3,enum=graphqlopt.Operation" json:"operation,omitempty"`   // override idempotency-based default
	OperationName string                 `protobuf:"bytes,3,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"` // override the GraphQL field name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_graphqlopt_graphql_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphqlopt_graphql_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_graphqlopt_graphql_proto_rawDescGZIP(), []int{2}
}

func (x *MethodOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *MethodOptions) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *MethodOptions) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

type MessageOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Skip          bool                   `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_graphqlopt_graphql_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphqlopt_graphql_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_graphqlopt_graphql_proto_rawDescGZIP(), []int{3}
}

func (x *MessageOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

type FieldOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Exclude       bool                   `protobuf:"varint,2,opt,name=exclude,proto3" json:"exclude,omitempty"`
	Scalar        string                 `protobuf:"bytes,3,opt,name=scalar,proto3" json:"scalar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_graphqlopt_graphql_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphqlopt_graphql_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_graphqlopt_graphql_proto_rawDescGZIP(), []int{4}
}

func (x *FieldOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldOptions) GetExclude() bool {
	if x != nil {
		return x.Exclude
	}
	return false
}

func (x *FieldOptions) GetScalar() string {
	if x != nil {
		return x.Scalar
	}
	return ""
}

type EnumOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumOptions) Reset() {
	*x = EnumOptions{}
	mi := &file_graphqlopt_graphql_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions) ProtoMessage() {}

func (x *EnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphqlopt_graphql_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOptions.ProtoReflect.Descriptor instead.
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return file_graphqlopt_graphql_proto_rawDescGZIP(), []int{5}
}

func (x *EnumOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OneofOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnionName     string                 `protobuf:"bytes,1,opt,name=union_name,json=unionName,proto3" json:"union_name,omitempty"`
	InputMode     OneofInputMode         `protobuf:"varint,2,opt,name=input_mode,json=inputMode,proto3,enum=graphqlopt.OneofInputMode" json:"input_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofOptions) Reset() {
	*x = OneofOptions{}
	mi := &file_graphqlopt_graphql_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofOptions) ProtoMessage() {}

func (x *OneofOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphqlopt_graphql_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofOptions.ProtoReflect.Descriptor instead.
func (*OneofOptions) Descriptor() ([]byte, []int) {
	return file_graphqlopt_graphql_proto_rawDescGZIP(), []int{6}
}

func (x *OneofOptions) GetUnionName() string {
	if x != nil {
		return x.UnionName
	}
	return ""
}

func (x *OneofOptions) GetInputMode() OneofInputMode {
	if x != nil {
		return x.InputMode
	}
	return OneofInputMode_ONEOF_INPUT_UNSPECIFIED
}

var file_graphqlopt_graphql_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         79000,
		Name:          "graphqlopt.file",
		Tag:           "bytes,79000,opt,name=file",
		Filename:      "graphqlopt/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         79000,
		Name:          "graphqlopt.service",
		Tag:           "bytes,79000,opt,name=service",
		Filename:      "graphqlopt/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         79000,
		Name:          "graphqlopt.method",
		Tag:           "bytes,79000,opt,name=method",
		Filename:      "graphqlopt/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         79000,
		Name:          "graphqlopt.message",
		Tag:           "bytes,79000,opt,name=message",
		Filename:      "graphqlopt/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         79000,
		Name:          "graphqlopt.field",
		Tag:           "bytes,79000,opt,name=field",
		Filename:      "graphqlopt/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumOptions)(nil),
		Field:         79000,
		Name:          "graphqlopt.enum",
		Tag:           "bytes,79000,opt,name=enum",
		Filename:      "graphqlopt/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*OneofOptions)(nil),
		Field:         79000,
		Name:          "graphqlopt.oneof",
		Tag:           "bytes,79000,opt,name=oneof",
		Filename:      "graphqlopt/graphql.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional graphqlopt.FileOptions file = 79000;
	E_File = &file_graphqlopt_graphql_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional graphqlopt.ServiceOptions service = 79000;
	E_Service = &file_graphqlopt_graphql_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional graphqlopt.MethodOptions method = 79000;
	E_Method = &file_graphqlopt_graphql_proto_extTypes[2]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional graphqlopt.MessageOptions message = 79000;
	E_Message = &file_graphqlopt_graphql_proto_extTypes[3]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional graphqlopt.FieldOptions field = 79000;
	E_Field = &file_graphqlopt_graphql_proto_extTypes[4]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional graphqlopt.EnumOptions enum = 79000;
	E_Enum = &file_graphqlopt_graphql_proto_extTypes[5]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional graphqlopt.OneofOptions oneof = 79000;
	E_Oneof = &file_graphqlopt_graphql_proto_extTypes[6]
)

var File_graphqlopt_graphql_proto protoreflect.FileDescriptor

const file_graphqlopt_graphql_proto_rawDesc = "" +
	"\n" +
	"\x18graphqlopt/graphql.proto\x12\n" +
	"graphqlopt\x1a google/protobuf/descriptor.proto\"\xd3\x01\n" +
	"\vFileOptions\x12\x1d\n" +
	"\n" +
	"pb_package\x18\x02 \x01(\tR\tpbPackage\x12'\n" +
	"\x0fschema_filename\x18\x03 \x01(\tR\x0eschemaFilename\x124\n" +
	"\x16gqlgen_config_filename\x18\x04 \x01(\tR\x14gqlgenConfigFilename\x12!\n" +
	"\fexec_package\x18\x05 \x01(\tR\vexecPackage\x12#\n" +
	"\rexec_filename\x18\x06 \x01(\tR\fexecFilename\"E\n" +
	"\x0eServiceOptions\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\bR\x04skip\x12\x1f\n" +
	"\vname_prefix\x18\x02 \x01(\tR\n" +
	"namePrefix\"\x7f\n" +
	"\rMethodOptions\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\bR\x04skip\x123\n" +
	"\toperation\x18\x02 \x01(\x0e2\x15.graphqlopt.OperationR\toperation\x12%\n" +
	"\x0eoperation_name\x18\x03 \x01(\tR\roperationName\"8\n" +
	"\x0eMessageOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\"T\n" +
	"\fFieldOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aexclude\x18\x02 \x01(\bR\aexclude\x12\x16\n" +
	"\x06scalar\x18\x03 \x01(\tR\x06scalar\"!\n" +
	"\vEnumOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"h\n" +
	"\fOneofOptions\x12\x1d\n" +
	"\n" +
	"union_name\x18\x01 \x01(\tR\tunionName\x129\n" +
	"\n" +
	"input_mode\x18\x02 \x01(\x0e2\x1a.graphqlopt.OneofInputModeR\tinputMode*Q\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05QUERY\x10\x01\x12\f\n" +
	"\bMUTATION\x10\x02\x12\x10\n" +
	"\fSUBSCRIPTION\x10\x03*T\n" +
	"\x0eOneofInputMode\x12\x1b\n" +
	"\x17ONEOF_INPUT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fONEOF_DIRECTIVE\x10\x01\x12\x10\n" +
	"\fALL_NULLABLE\x10\x02:K\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18\x98\xe9\x04 \x01(\v2\x17.graphqlopt.FileOptionsR\x04file:W\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\x98\xe9\x04 \x01(\v2\x1a.graphqlopt.ServiceOptionsR\aservice:S\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18\x98\xe9\x04 \x01(\v2\x19.graphqlopt.MethodOptionsR\x06method:W\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\x98\xe9\x04 \x01(\v2\x1a.graphqlopt.MessageOptionsR\amessage:O\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\x98\xe9\x04 \x01(\v2\x18.graphqlopt.FieldOptionsR\x05field:K\n" +
	"\x04enum\x12\x1c.google.protobuf.EnumOptions\x18\x98\xe9\x04 \x01(\v2\x17.graphqlopt.EnumOptionsR\x04enum:O\n" +
	"\x05oneof\x12\x1d.google.protobuf.OneofOptions\x18\x98\xe9\x04 \x01(\v2\x18.graphqlopt.OneofOptionsR\x05oneofBAZ?github.com/gopherex/protoc-gen-go-graphql/graphqlopt;graphqloptb\x06proto3"

var (
	file_graphqlopt_graphql_proto_rawDescOnce sync.Once
	file_graphqlopt_graphql_proto_rawDescData []byte
)

func file_graphqlopt_graphql_proto_rawDescGZIP() []byte {
	file_graphqlopt_graphql_proto_rawDescOnce.Do(func() {
		file_graphqlopt_graphql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graphqlopt_graphql_proto_rawDesc), len(file_graphqlopt_graphql_proto_rawDesc)))
	})
	return file_graphqlopt_graphql_proto_rawDescData
}

var file_graphqlopt_graphql_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_graphqlopt_graphql_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_graphqlopt_graphql_proto_goTypes = []any{
	(Operation)(0),                      // 0: graphqlopt.Operation
	(OneofInputMode)(0),                 // 1: graphqlopt.OneofInputMode
	(*FileOptions)(nil),                 // 2: graphqlopt.FileOptions
	(*ServiceOptions)(nil),              // 3: graphqlopt.ServiceOptions
	(*MethodOptions)(nil),               // 4: graphqlopt.MethodOptions
	(*MessageOptions)(nil),              // 5: graphqlopt.MessageOptions
	(*FieldOptions)(nil),                // 6: graphqlopt.FieldOptions
	(*EnumOptions)(nil),                 // 7: graphqlopt.EnumOptions
	(*OneofOptions)(nil),                // 8: graphqlopt.OneofOptions
	(*descriptorpb.FileOptions)(nil),    // 9: google.protobuf.FileOptions
	(*descriptorpb.ServiceOptions)(nil), // 10: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 11: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 12: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 13: google.protobuf.FieldOptions
	(*descriptorpb.EnumOptions)(nil),    // 14: google.protobuf.EnumOptions
	(*descriptorpb.OneofOptions)(nil),   // 15: google.protobuf.OneofOptions
}
var file_graphqlopt_graphql_proto_depIdxs = []int32{
	0,  // 0: graphqlopt.MethodOptions.operation:type_name -> graphqlopt.Operation
	1,  // 1: graphqlopt.OneofOptions.input_mode:type_name -> graphqlopt.OneofInputMode
	9,  // 2: graphqlopt.file:extendee -> google.protobuf.FileOptions
	10, // 3: graphqlopt.service:extendee -> google.protobuf.ServiceOptions
	11, // 4: graphqlopt.method:extendee -> google.protobuf.MethodOptions
	12, // 5: graphqlopt.message:extendee -> google.protobuf.MessageOptions
	13, // 6: graphqlopt.field:extendee -> google.protobuf.FieldOptions
	14, // 7: graphqlopt.enum:extendee -> google.protobuf.EnumOptions
	15, // 8: graphqlopt.oneof:extendee -> google.protobuf.OneofOptions
	2,  // 9: graphqlopt.file:type_name -> graphqlopt.FileOptions
	3,  // 10: graphqlopt.service:type_name -> graphqlopt.ServiceOptions
	4,  // 11: graphqlopt.method:type_name -> graphqlopt.MethodOptions
	5,  // 12: graphqlopt.message:type_name -> graphqlopt.MessageOptions
	6,  // 13: graphqlopt.field:type_name -> graphqlopt.FieldOptions
	7,  // 14: graphqlopt.enum:type_name -> graphqlopt.EnumOptions
	8,  // 15: graphqlopt.oneof:type_name -> graphqlopt.OneofOptions
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	9,  // [9:16] is the sub-list for extension type_name
	2,  // [2:9] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_graphqlopt_graphql_proto_init() }
func file_graphqlopt_graphql_proto_init() {
	if File_graphqlopt_graphql_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graphqlopt_graphql_proto_rawDesc), len(file_graphqlopt_graphql_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 7,
			NumServices:   0,
		},
		GoTypes:           file_graphqlopt_graphql_proto_goTypes,
		DependencyIndexes: file_graphqlopt_graphql_proto_depIdxs,
		EnumInfos:         file_graphqlopt_graphql_proto_enumTypes,
		MessageInfos:      file_graphqlopt_graphql_proto_msgTypes,
		ExtensionInfos:    file_graphqlopt_graphql_proto_extTypes,
	}.Build()
	File_graphqlopt_graphql_proto = out.File
	file_graphqlopt_graphql_proto_goTypes = nil
	file_graphqlopt_graphql_proto_depIdxs = nil
}
