// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: golden.proto

package gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Library_GetEverything_FullMethodName = "/golden.v1.Library/GetEverything"
	Library_GetScalars_FullMethodName    = "/golden.v1.Library/GetScalars"
	Library_SearchBooks_FullMethodName   = "/golden.v1.Library/SearchBooks"
	Library_Lookup_FullMethodName        = "/golden.v1.Library/Lookup"
	Library_Ping_FullMethodName          = "/golden.v1.Library/Ping"
	Library_GetThing_FullMethodName      = "/golden.v1.Library/GetThing"
	Library_EchoInput_FullMethodName     = "/golden.v1.Library/EchoInput"
	Library_AddBook_FullMethodName       = "/golden.v1.Library/AddBook"
	Library_UpsertBook_FullMethodName    = "/golden.v1.Library/UpsertBook"
	Library_WatchItems_FullMethodName    = "/golden.v1.Library/WatchItems"
	Library_ShipLogs_FullMethodName      = "/golden.v1.Library/ShipLogs"
)

// LibraryClient is the client API for Library service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LibraryClient interface {
	// Queries (NO_SIDE_EFFECTS → Query root).
	GetEverything(ctx context.Context, in *GetEverythingRequest, opts ...grpc.CallOption) (*GetEverythingResponse, error)
	// operation_name override: the GraphQL field is renamed to "fetchScalars".
	GetScalars(ctx context.Context, in *GetScalarsRequest, opts ...grpc.CallOption) (*GetScalarsResponse, error)
	SearchBooks(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Lookup: input oneof in ALL_NULLABLE mode → plain input object (no @oneOf),
	// exactly-one enforced at runtime in the ToPb shim. Reuses SearchResponse.
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Empty request and response (fieldless messages).
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// B1 option coverage: message rename + field rename + field exclude,
	// exercised end-to-end through gqlgen.
	GetThing(ctx context.Context, in *GetThingRequest, opts ...grpc.CallOption) (*GetThingResponse, error)
	// Mutations (default → Mutation root).
	EchoInput(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error)
	// Idempotent mutation: upsert a book (IDEMPOTENT → @idempotent directive).
	UpsertBook(ctx context.Context, in *UpsertBookRequest, opts ...grpc.CallOption) (*UpsertBookResponse, error)
	// Subscription (server-streaming → Subscription root).
	WatchItems(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	// Client-streaming rpc marked skip: unsupported shape, but skip suppresses
	// the fail-fast so generation proceeds. ShipLogs is absent from the schema.
	ShipLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogChunk, ShipAck], error)
}

type libraryClient struct {
	cc grpc.ClientConnInterface
}

func NewLibraryClient(cc grpc.ClientConnInterface) LibraryClient {
	return &libraryClient{cc}
}

func (c *libraryClient) GetEverything(ctx context.Context, in *GetEverythingRequest, opts ...grpc.CallOption) (*GetEverythingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEverythingResponse)
	err := c.cc.Invoke(ctx, Library_GetEverything_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) GetScalars(ctx context.Context, in *GetScalarsRequest, opts ...grpc.CallOption) (*GetScalarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScalarsResponse)
	err := c.cc.Invoke(ctx, Library_GetScalars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) SearchBooks(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Library_SearchBooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Library_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Library_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) GetThing(ctx context.Context, in *GetThingRequest, opts ...grpc.CallOption) (*GetThingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThingResponse)
	err := c.cc.Invoke(ctx, Library_GetThing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) EchoInput(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, Library_EchoInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBookResponse)
	err := c.cc.Invoke(ctx, Library_AddBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) UpsertBook(ctx context.Context, in *UpsertBookRequest, opts ...grpc.CallOption) (*UpsertBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertBookResponse)
	err := c.cc.Invoke(ctx, Library_UpsertBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) WatchItems(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Library_ServiceDesc.Streams[0], Library_WatchItems_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Library_WatchItemsClient = grpc.ServerStreamingClient[WatchEvent]

func (c *libraryClient) ShipLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogChunk, ShipAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Library_ServiceDesc.Streams[1], Library_ShipLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogChunk, ShipAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Library_ShipLogsClient = grpc.ClientStreamingClient[LogChunk, ShipAck]

// LibraryServer is the server API for Library service.
// All implementations must embed UnimplementedLibraryServer
// for forward compatibility.
type LibraryServer interface {
	// Queries (NO_SIDE_EFFECTS → Query root).
	GetEverything(context.Context, *GetEverythingRequest) (*GetEverythingResponse, error)
	// operation_name override: the GraphQL field is renamed to "fetchScalars".
	GetScalars(context.Context, *GetScalarsRequest) (*GetScalarsResponse, error)
	SearchBooks(context.Context, *SearchRequest) (*SearchResponse, error)
	// Lookup: input oneof in ALL_NULLABLE mode → plain input object (no @oneOf),
	// exactly-one enforced at runtime in the ToPb shim. Reuses SearchResponse.
	Lookup(context.Context, *LookupRequest) (*SearchResponse, error)
	// Empty request and response (fieldless messages).
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// B1 option coverage: message rename + field rename + field exclude,
	// exercised end-to-end through gqlgen.
	GetThing(context.Context, *GetThingRequest) (*GetThingResponse, error)
	// Mutations (default → Mutation root).
	EchoInput(context.Context, *EchoRequest) (*EchoResponse, error)
	AddBook(context.Context, *AddBookRequest) (*AddBookResponse, error)
	// Idempotent mutation: upsert a book (IDEMPOTENT → @idempotent directive).
	UpsertBook(context.Context, *UpsertBookRequest) (*UpsertBookResponse, error)
	// Subscription (server-streaming → Subscription root).
	WatchItems(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	// Client-streaming rpc marked skip: unsupported shape, but skip suppresses
	// the fail-fast so generation proceeds. ShipLogs is absent from the schema.
	ShipLogs(grpc.ClientStreamingServer[LogChunk, ShipAck]) error
	mustEmbedUnimplementedLibraryServer()
}

// UnimplementedLibraryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLibraryServer struct{}

func (UnimplementedLibraryServer) GetEverything(context.Context, *GetEverythingRequest) (*GetEverythingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEverything not implemented")
}
func (UnimplementedLibraryServer) GetScalars(context.Context, *GetScalarsRequest) (*GetScalarsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScalars not implemented")
}
func (UnimplementedLibraryServer) SearchBooks(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchBooks not implemented")
}
func (UnimplementedLibraryServer) Lookup(context.Context, *LookupRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedLibraryServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLibraryServer) GetThing(context.Context, *GetThingRequest) (*GetThingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThing not implemented")
}
func (UnimplementedLibraryServer) EchoInput(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EchoInput not implemented")
}
func (UnimplementedLibraryServer) AddBook(context.Context, *AddBookRequest) (*AddBookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBook not implemented")
}
func (UnimplementedLibraryServer) UpsertBook(context.Context, *UpsertBookRequest) (*UpsertBookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertBook not implemented")
}
func (UnimplementedLibraryServer) WatchItems(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchItems not implemented")
}
func (UnimplementedLibraryServer) ShipLogs(grpc.ClientStreamingServer[LogChunk, ShipAck]) error {
	return status.Error(codes.Unimplemented, "method ShipLogs not implemented")
}
func (UnimplementedLibraryServer) mustEmbedUnimplementedLibraryServer() {}
func (UnimplementedLibraryServer) testEmbeddedByValue()                 {}

// UnsafeLibraryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LibraryServer will
// result in compilation errors.
type UnsafeLibraryServer interface {
	mustEmbedUnimplementedLibraryServer()
}

func RegisterLibraryServer(s grpc.ServiceRegistrar, srv LibraryServer) {
	// If the following call panics, it indicates UnimplementedLibraryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Library_ServiceDesc, srv)
}

func _Library_GetEverything_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEverythingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).GetEverything(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Library_GetEverything_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).GetEverything(ctx, req.(*GetEverythingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_GetScalars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScalarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).GetScalars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Library_GetScalars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).GetScalars(ctx, req.(*GetScalarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_SearchBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).SearchBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Library_SearchBooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).SearchBooks(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Library_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Library_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_GetThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).GetThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Library_GetThing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).GetThing(ctx, req.(*GetThingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_EchoInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).EchoInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Library_EchoInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).EchoInput(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Library_AddBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).AddBook(ctx, req.(*AddBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_UpsertBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).UpsertBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Library_UpsertBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).UpsertBook(ctx, req.(*UpsertBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_WatchItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LibraryServer).WatchItems(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Library_WatchItemsServer = grpc.ServerStreamingServer[WatchEvent]

func _Library_ShipLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LibraryServer).ShipLogs(&grpc.GenericServerStream[LogChunk, ShipAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Library_ShipLogsServer = grpc.ClientStreamingServer[LogChunk, ShipAck]

// Library_ServiceDesc is the grpc.ServiceDesc for Library service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Library_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "golden.v1.Library",
	HandlerType: (*LibraryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEverything",
			Handler:    _Library_GetEverything_Handler,
		},
		{
			MethodName: "GetScalars",
			Handler:    _Library_GetScalars_Handler,
		},
		{
			MethodName: "SearchBooks",
			Handler:    _Library_SearchBooks_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _Library_Lookup_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Library_Ping_Handler,
		},
		{
			MethodName: "GetThing",
			Handler:    _Library_GetThing_Handler,
		},
		{
			MethodName: "EchoInput",
			Handler:    _Library_EchoInput_Handler,
		},
		{
			MethodName: "AddBook",
			Handler:    _Library_AddBook_Handler,
		},
		{
			MethodName: "UpsertBook",
			Handler:    _Library_UpsertBook_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchItems",
			Handler:       _Library_WatchItems_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ShipLogs",
			Handler:       _Library_ShipLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "golden.proto",
}
