// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: multipkg/models/models.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message-only package (no services). Imported by the API package below.
type Widget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Widget) Reset() {
	*x = Widget{}
	mi := &file_multipkg_models_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Widget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Widget) ProtoMessage() {}

func (x *Widget) ProtoReflect() protoreflect.Message {
	mi := &file_multipkg_models_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Widget.ProtoReflect.Descriptor instead.
func (*Widget) Descriptor() ([]byte, []int) {
	return file_multipkg_models_models_proto_rawDescGZIP(), []int{0}
}

func (x *Widget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Widget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_multipkg_models_models_proto protoreflect.FileDescriptor

const file_multipkg_models_models_proto_rawDesc = "" +
	"\n" +
	"\x1cmultipkg/models/models.proto\x12\x12multipkg.models.v1\",\n" +
	"\x06Widget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameBJZHgithub.com/gopherex/protoc-gen-go-graphql/example/multipkg/models;modelsb\x06proto3"

var (
	file_multipkg_models_models_proto_rawDescOnce sync.Once
	file_multipkg_models_models_proto_rawDescData []byte
)

func file_multipkg_models_models_proto_rawDescGZIP() []byte {
	file_multipkg_models_models_proto_rawDescOnce.Do(func() {
		file_multipkg_models_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multipkg_models_models_proto_rawDesc), len(file_multipkg_models_models_proto_rawDesc)))
	})
	return file_multipkg_models_models_proto_rawDescData
}

var file_multipkg_models_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_multipkg_models_models_proto_goTypes = []any{
	(*Widget)(nil), // 0: multipkg.models.v1.Widget
}
var file_multipkg_models_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multipkg_models_models_proto_init() }
func file_multipkg_models_models_proto_init() {
	if File_multipkg_models_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multipkg_models_models_proto_rawDesc), len(file_multipkg_models_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multipkg_models_models_proto_goTypes,
		DependencyIndexes: file_multipkg_models_models_proto_depIdxs,
		MessageInfos:      file_multipkg_models_models_proto_msgTypes,
	}.Build()
	File_multipkg_models_models_proto = out.File
	file_multipkg_models_models_proto_goTypes = nil
	file_multipkg_models_models_proto_depIdxs = nil
}
