// Code generated by protoc-gen-go-graphql. DO NOT EDIT.
package gqlapi

import (
	"context"

	pb "github.com/gopherex/protoc-gen-go-graphql/example/multipkg/api"
	"github.com/gopherex/protoc-gen-go-graphql/example/multipkg/api/gqlapi/exec"
	"github.com/gopherex/protoc-gen-go-graphql/graphqlpb"
)

// Resolver delegates GraphQL operations to the gRPC server implementation.
// It implements exec.ResolverRoot and each sub-resolver interface,
// delegating to the gRPC server with zero proto<->model conversion.
type Resolver struct {
	WidgetService pb.WidgetServiceServer
}

func (r *Resolver) Query() exec.QueryResolver { return queryResolver{r} }

type queryResolver struct{ *Resolver }

func (r queryResolver) GetWidget(ctx context.Context, input pb.GetWidgetRequest) (*pb.GetWidgetResponse, error) {
	resp, err := r.WidgetService.GetWidget(ctx, &input)
	if err != nil {
		return nil, graphqlpb.GraphQLError(ctx, err)
	}
	return resp, nil
}
