// Code generated by protoc-gen-go-graphql (graphql-go backend). DO NOT EDIT.
package gqlapi

import (
	"context"

	pb "github.com/gopherex/protoc-gen-go-graphql/example/multipkg/api"
	pb1 "github.com/gopherex/protoc-gen-go-graphql/example/multipkg/models"
	graphqlrt "github.com/gopherex/protoc-gen-go-graphql/graphqlrt"
	"github.com/graphql-go/graphql"
)

// Server holds the gRPC service implementations the schema delegates to.
type Server struct {
	WidgetService pb.WidgetServiceServer
	// Authorize, when set, runs before each operation delegates to its gRPC
	// method, receiving the gRPC procedure name and decoded request, to enforce
	// the same per-method authn+authz as the connect/gRPC interceptors. It
	// returns the (identity-enriched) context to delegate with.
	Authorize func(ctx context.Context, procedure string, req interface{}) (context.Context, error)
}

func decode_GetWidgetRequest(m map[string]interface{}) *pb.GetWidgetRequest {
	out := &pb.GetWidgetRequest{}
	if m == nil {
		return out
	}
	out.Id = graphqlrt.AsString(m["id"])
	return out
}

// NewSchema builds the executable GraphQL schema bound to srv.
func NewSchema(srv *Server) (graphql.Schema, error) {
	var o_GetWidgetResponse *graphql.Object
	var o_Widget *graphql.Object
	var i_GetWidgetRequest *graphql.InputObject
	o_GetWidgetResponse = graphql.NewObject(graphql.ObjectConfig{Name: "GetWidgetResponse", Fields: graphql.FieldsThunk(func() graphql.Fields {
		return graphql.Fields{
			"widget": &graphql.Field{Type: o_Widget, Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				obj, _ := p.Source.(*pb.GetWidgetResponse)
				if obj == nil {
					return nil, nil
				}
				return obj.GetWidget(), nil
			}},
		}
	})})
	o_Widget = graphql.NewObject(graphql.ObjectConfig{Name: "Widget", Fields: graphql.FieldsThunk(func() graphql.Fields {
		return graphql.Fields{
			"id": &graphql.Field{Type: graphql.NewNonNull(graphql.String), Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				obj, _ := p.Source.(*pb1.Widget)
				if obj == nil {
					return nil, nil
				}
				return obj.GetId(), nil
			}},
			"name": &graphql.Field{Type: graphql.NewNonNull(graphql.String), Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				obj, _ := p.Source.(*pb1.Widget)
				if obj == nil {
					return nil, nil
				}
				return obj.GetName(), nil
			}},
		}
	})})
	i_GetWidgetRequest = graphql.NewInputObject(graphql.InputObjectConfig{Name: "GetWidgetRequest", Fields: graphql.InputObjectConfigFieldMapThunk(func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"id": &graphql.InputObjectFieldConfig{Type: graphql.NewNonNull(graphql.String)},
		}
	})})
	queryRoot := graphql.NewObject(graphql.ObjectConfig{Name: "Query", Fields: graphql.Fields{
		"getWidget": &graphql.Field{Type: o_GetWidgetResponse, Args: graphql.FieldConfigArgument{
			"id": &graphql.ArgumentConfig{Type: graphql.NewNonNull(graphql.String)},
		}, Resolve: func(p graphql.ResolveParams) (interface{}, error) {
			req := decode_GetWidgetRequest(p.Args)
			ctx := p.Context
			if srv.Authorize != nil {
				var aerr error
				ctx, aerr = srv.Authorize(ctx, "/multipkg.api.v1.WidgetService/GetWidget", req)
				if aerr != nil {
					return nil, graphqlrt.GraphQLError(ctx, aerr)
				}
			}
			resp, err := srv.WidgetService.GetWidget(ctx, req)
			if err != nil {
				return nil, graphqlrt.GraphQLError(ctx, err)
			}
			return resp, nil
		}},
	}})
	cfg := graphql.SchemaConfig{}
	cfg.Query = queryRoot
	cfg.Types = []graphql.Type{o_GetWidgetResponse, o_Widget, i_GetWidgetRequest}
	return graphql.NewSchema(cfg)
}
