// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: multipkg/api/api.proto

package api

import (
	models "github.com/gopherex/protoc-gen-go-graphql/example/multipkg/models"
	_ "github.com/gopherex/protoc-gen-go-graphql/graphqlopt"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWidgetRequest) Reset() {
	*x = GetWidgetRequest{}
	mi := &file_multipkg_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWidgetRequest) ProtoMessage() {}

func (x *GetWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipkg_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWidgetRequest.ProtoReflect.Descriptor instead.
func (*GetWidgetRequest) Descriptor() ([]byte, []int) {
	return file_multipkg_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetWidgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWidgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Widget        *models.Widget         `protobuf:"bytes,1,opt,name=widget,proto3" json:"widget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWidgetResponse) Reset() {
	*x = GetWidgetResponse{}
	mi := &file_multipkg_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWidgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWidgetResponse) ProtoMessage() {}

func (x *GetWidgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipkg_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWidgetResponse.ProtoReflect.Descriptor instead.
func (*GetWidgetResponse) Descriptor() ([]byte, []int) {
	return file_multipkg_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetWidgetResponse) GetWidget() *models.Widget {
	if x != nil {
		return x.Widget
	}
	return nil
}

var File_multipkg_api_api_proto protoreflect.FileDescriptor

const file_multipkg_api_api_proto_rawDesc = "" +
	"\n" +
	"\x16multipkg/api/api.proto\x12\x0fmultipkg.api.v1\x1a\x18graphqlopt/graphql.proto\x1a\x1cmultipkg/models/models.proto\"\"\n" +
	"\x10GetWidgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x11GetWidgetResponse\x122\n" +
	"\x06widget\x18\x01 \x01(\v2\x1a.multipkg.models.v1.WidgetR\x06widget2h\n" +
	"\rWidgetService\x12W\n" +
	"\tGetWidget\x12!.multipkg.api.v1.GetWidgetRequest\x1a\".multipkg.api.v1.GetWidgetResponse\"\x03\x90\x02\x01BDZBgithub.com/gopherex/protoc-gen-go-graphql/example/multipkg/api;apib\x06proto3"

var (
	file_multipkg_api_api_proto_rawDescOnce sync.Once
	file_multipkg_api_api_proto_rawDescData []byte
)

func file_multipkg_api_api_proto_rawDescGZIP() []byte {
	file_multipkg_api_api_proto_rawDescOnce.Do(func() {
		file_multipkg_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multipkg_api_api_proto_rawDesc), len(file_multipkg_api_api_proto_rawDesc)))
	})
	return file_multipkg_api_api_proto_rawDescData
}

var file_multipkg_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_multipkg_api_api_proto_goTypes = []any{
	(*GetWidgetRequest)(nil),  // 0: multipkg.api.v1.GetWidgetRequest
	(*GetWidgetResponse)(nil), // 1: multipkg.api.v1.GetWidgetResponse
	(*models.Widget)(nil),     // 2: multipkg.models.v1.Widget
}
var file_multipkg_api_api_proto_depIdxs = []int32{
	2, // 0: multipkg.api.v1.GetWidgetResponse.widget:type_name -> multipkg.models.v1.Widget
	0, // 1: multipkg.api.v1.WidgetService.GetWidget:input_type -> multipkg.api.v1.GetWidgetRequest
	1, // 2: multipkg.api.v1.WidgetService.GetWidget:output_type -> multipkg.api.v1.GetWidgetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_multipkg_api_api_proto_init() }
func file_multipkg_api_api_proto_init() {
	if File_multipkg_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multipkg_api_api_proto_rawDesc), len(file_multipkg_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multipkg_api_api_proto_goTypes,
		DependencyIndexes: file_multipkg_api_api_proto_depIdxs,
		MessageInfos:      file_multipkg_api_api_proto_msgTypes,
	}.Build()
	File_multipkg_api_api_proto = out.File
	file_multipkg_api_api_proto_goTypes = nil
	file_multipkg_api_api_proto_depIdxs = nil
}
